CREATE SCHEMA IF NOT EXISTS mpapi;

SET SCHEMA mpapi;

CREATE TABLE IF NOT EXISTS PRODUCTS(
    ID int NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR NOT NULL,
    ARTIST VARCHAR NOT NULL,
    LABEL VARCHAR NOT NULL,
    PRICE_GBP VARCHAR NOT NULL,
    PRICE_USD VARCHAR NOT NULL,
    PRICE_EUR VARCHAR NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    STORE VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);


